export const SKI_DESTINATIONS = [
  'Åre',
  'Sälen',
  'Val Thorens',
  'Val d\'Isère',
  'Cervinia',
  'Zermatt',
  'Ischgl',
  'Engelberg',
  'Chamonix',
  'St. Anton',
  'Saalbach',
  'Verbier',
  'Kitzbühel',
  'Sauze d\'Oulx',
  'Cortina d\'Ampezzo',
  'Courchevel',
  'Méribel',
  'Les Arcs',
  'La Plagne',
  'Tignes',
  'Alpe d\'Huez',
  'Les Deux Alpes',
  'Avoriaz',
  'Flaine',
  'Livigno',
  'Trysil',
  'Hemsedal',
  'Riksgränsen',
  'Mayrhofen',
  'Zell am See',
  'Bad Gastein',
  'Avoriaz',
  'Madonna di Campiglio'
];

export const SKI_DESTINATION_DESCRIPTIONS = {
  'Åre': 'Åre är Sveriges främsta alpina destination med en mix av branta pister, snowparks och natursnö. Orten bjuder på ett pulserande nattliv, med barer och klubbar som lockar unga resenärer och afterski-entusiaster.',
  'Sälen': 'Sälen är en familjevänlig skidort med flera skidsystem, moderna liftar och lättillgängliga backar. Här finns också ett växande utbud av afterski och restauranger, särskilt i Lindvallen och Hundfjället.',
  'Val Thorens': 'Europas högst belägna skidort erbjuder snösäker skidåkning i världsklass. Som del av Les Trois Vallées har du tillgång till över 600 km pister. Val Thorens är också känd för sitt intensiva nattliv och populära afterski.',
  'Val d\'Isère': 'En av Alpernas mest ikoniska orter, Val d\'Isère kombinerar högklassig skidåkning med charmig bykänsla. Här finns tekniska pister, fantastisk offpist, lyxiga hotell och ett nattliv med internationell prägel.',
  'Cervinia': 'Cervinia ligger vid foten av Matterhorn och erbjuder breda, långa pister och fantastisk utsikt. Du kan även åka över till Zermatt. Orten har ett lugnare nattliv, men flera mysiga restauranger och barer.',
  'Zermatt': 'Zermatt är en exklusiv schweizisk ort med panoramavy över Matterhorn. Här hittar du helårsskidakning, ett imponerande pistnätverk och en elegant bymiljö med gourmetrestauranger och sofistikerade barer.',
  'Ischgl': 'Ischgl är känt för sina stora afterski-fester, internationella konserter och ett enormt skidområde. Perfekt för åkare som vill kombinera skidåkning med fest i världsklass.',
  'Engelberg': 'Engelberg bjuder på dramatisk alpnatur, djupt puder och teknisk offpist. Det är en favorit bland friåkare och har ett mer avslappnat nattliv med fokus på afterski och pubmiljö.',
  'Chamonix': 'Chamonix är epicentrum för extremskidåkning i Europa. Här finns branta berg, glaciärer och legendarisk offpist. Nattlivet är varierat och lockar internationella äventyrare och bergsguider.',
  'St. Anton': 'St. Anton är känt för sin avancerade skidåkning, djupa snö och några av Alpernas mest legendariska afterski-ställen som MooserWirt. Perfekt för erfarna åkare och festglada resenärer.',
  'Saalbach': 'Saalbach-Hinterglemm erbjuder över 270 km pist och ett av Österrikes mest sammanhängande skidsystem. Här kombineras familjevänlig åkning med ett livligt nattliv och klassisk afterski.',
  'Verbier': 'Verbier är exklusivt, sportigt och stilrent. Orten är känd för sin freeride-kultur, branta pister och glamorösa nattliv. Här möts adrenalin och elegans.',
  'Kitzbühel': 'Kitzbühel har både historia och stil. Den legendariska Hahnenkamm-backen utmanar eliten, medan byn erbjuder shopping, gourmet och ett levande kvällsliv.',
  'Sauze d\'Oulx': 'En charmig italiensk skidort i Via Lattea-systemet. Sauze d’Oulx har ett avslappnat nattliv, breda pister och ett prisvärt alternativ för ungdomar och grupper.',
  'Cortina d\'Ampezzo': 'Cortina kombinerar italiensk elegans med fantastisk skidåkning i Dolomiterna. Här möts vacker natur, breda pister och en mondän atmosfär med exklusiva barer och modebutiker.',
  'Courchevel': 'En av världens mest exklusiva skidorter. Courchevel erbjuder lyxhotell, Michelinrestauranger och perfekt preparerade pister. Nattlivet är sofistikerat och internationellt.',
  'Méribel': 'Méribel har en charmig alpin arkitektur och ett centralt läge i Les Trois Vallées. Här blandas sportiga resenärer med barnfamiljer och det finns gott om afterski och pubar.',
  'Les Arcs': 'Les Arcs är modernt och varierat med pister i alla svårighetsgrader. Här finns både ski-in/ski-out-logi och ett avslappnat nattliv som lockar yngre resenärer.',
  'La Plagne': 'Perfekt för grupper med olika nivåer. La Plagne har många blå och röda pister samt en glaciär. Utbudet av barer är stort, särskilt i Belle Plagne.',
  'Tignes': 'Tignes erbjuder snösäker skidåkning och glaciäråkning året runt. Orten är sportig, ungdomlig och har en livlig afterski-scen.',
  'Alpe d\'Huez': 'Känd för sin sol och de långa, varierade nedfarterna. Alpe d’Huez erbjuder fantastisk utsikt, breda pister och en aktiv afterski-kultur.',
  'Les Deux Alpes': 'Här finns både glaciäråkning och snowparks. Orten är prisvärd och ungdomlig, med mycket liv på kvällarna och många barer.',
  'Avoriaz': 'Avoriaz är bilfri, modern och mitt i enorma Portes du Soleil. Orten är populär bland unga, med många barer och ett bra utgångsläge för både park och pist.',
  'Flaine': 'Flaine ligger högt och har gott om snö, breda backar och lättåtkomlig offpist. Orten är funktionell med fokus på skidåkning snarare än nattliv.',
  'Livigno': 'Livigno erbjuder skattefri shopping, breda pister och bra priser. Perfekt för en längre vistelse med fokus på både åkning och nöje.',
  'Trysil': 'Trysil är Norges största skidort och passar hela familjen. Det moderna liftsystemet och varierade backar kompletteras med mysig afterski och barhäng.',
  'Hemsedal': 'Ofta kallad Skandinaviens Alper. Hemsedal bjuder på utmanande terräng, bra snö och en ungdomlig stämning med fartfyllda kvällar.',
  'Riksgränsen': 'Sveriges nordligaste skidort är unik med sin vårsäsong, offpist och möjligheten till midnattssol. Perfekt för äventyrslystna.',
  'Mayrhofen': 'Mayrhofen kombinerar tillgång till Hintertux-glaciären med en av Alpernas bästa afterski-scener. Orten är prisvärd och populär bland ungdomar.',
  'Zell am See': 'Zell am See är en klassisk skidort vid sjön, med tillgång till glaciär och en mysig stadskärna. Perfekt för både skidåkning och avkoppling.',
  'Bad Gastein': 'Kurortskänsla möter skidåkning. Bad Gastein bjuder på både termalbad, imponerande berg och ett nattliv som överraskar.',
  'Madonna di Campiglio': 'Denna italienska pärla i Dolomiterna kombinerar exklusiv atmosfär med välpreparerade pister och stilfulla barer. Ett elegant val för finsmakaren.'
};