export const SKI_DESTINATION_STATS = {
  'Åre': { price: 2, sights: 4, nightlife: 5 },
  'Sälen': { price: 3, sights: 3, nightlife: 3 },
  'Val Thorens': { price: 1, sights: 5, nightlife: 4 },
  'Val d\'Isère': { price: 1, sights: 5, nightlife: 5 },
  'Cervinia': { price: 2, sights: 4, nightlife: 3 },
  'Zermatt': { price: 1, sights: 5, nightlife: 4 },
  'Ischgl': { price: 2, sights: 4, nightlife: 5 },
  'Engelberg': { price: 2, sights: 4, nightlife: 3 },
  'Chamonix': { price: 2, sights: 5, nightlife: 4 },
  'St. Anton': { price: 2, sights: 4, nightlife: 5 },
  'Saalbach': { price: 3, sights: 4, nightlife: 5 },
  'Verbier': { price: 1, sights: 5, nightlife: 5 },
  'Kitzbühel': { price: 2, sights: 5, nightlife: 4 },
  'Sauze d\'Oulx': { price: 4, sights: 3, nightlife: 4 },
  'Cortina d\'Ampezzo': { price: 2, sights: 5, nightlife: 3 },
  'Courchevel': { price: 1, sights: 5, nightlife: 4 },
  'Méribel': { price: 2, sights: 4, nightlife: 4 },
  'Les Arcs': { price: 3, sights: 4, nightlife: 3 },
  'La Plagne': { price: 3, sights: 4, nightlife: 4 },
  'Tignes': { price: 2, sights: 4, nightlife: 4 },
  'Alpe d\'Huez': { price: 3, sights: 4, nightlife: 4 },
  'Les Deux Alpes': { price: 3, sights: 4, nightlife: 4 },
  'Avoriaz': { price: 3, sights: 4, nightlife: 3 },
  'Flaine': { price: 3, sights: 3, nightlife: 3 },
  'Livigno': { price: 4, sights: 4, nightlife: 4 },
  'Trysil': { price: 3, sights: 4, nightlife: 3 },
'Hemsedal': { price: 3, sights: 4, nightlife: 4 },
'Riksgränsen': { price: 2, sights: 3, nightlife: 2 },
'Mayrhofen': { price: 4, sights: 4, nightlife: 5 },
'Zell am See': { price: 3, sights: 4, nightlife: 4 },
'Bad Gastein': { price: 3, sights: 4, nightlife: 5 },
'Avoriaz': { price: 2, sights: 5, nightlife: 4 },
'Madonna di Campiglio': { price: 2, sights: 5, nightlife: 3 },

};